### ISSUE TITLE
<Fragment></Fragment> can just be <></>

### ISSUE THREAD

**Issue by ClayTaeto** [tylersb/ezchat#11]
i don't think people use the actual component <Fragment></Fragment>, just use <></>
you don't need to import anything, just throw in a good ol <>

**Comment by tylersb** [comment]
Thanks, I removed the only one I found which was in MetaPanelDrawer but if you meant a different one let me know. I couldn't figure out why it was even there at first since I only import Fragment if I need to add a key attribute to a fragment, which short syntax doesn't allow for. Eventually realized it was there because it was an MUI component I had copy/pasted straight in and hadn't edited or tweaked it since I don't think I ended up using it.
