### ISSUE TITLE
channel select seems to be removed

### ISSUE THREAD

**Issue by ClayTaeto** [tylersb/ezchat#7]
prob the recent changes to regular/admin users that broke being able to view/add channels

**Comment by tylersb** [comment]
I tested it out with a new account to check and it seems to be working, although I think the wording probably needs some tweaks. Currently there's no list of channels (opted not to have any default or globally available channels in case anybody uses an anonymous login and posts anything inappropriate since this is a project for my portfolio).

The only way to join another channel is if you already know the Channel ID, here's one that should lead to a Gaming channel: H6bLD8nWSTRv0AtJiCJ1
